WebApplication1/Controllers/CustomersController.cs
using WebApplication1.Filters;
using Ionic.Zip;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1;

namespace WebApplication1.Controllers
{
    [AutorizeUser]
    public class CustomersController : Controller
    {
        private IdCardDataManagerEntities1 db = new IdCardDataManagerEntities1();

        // GET: Customers
        [AutorizeUser]
        public ActionResult Index()
        {

            
            
            return View();
        }

        // GET: Customers/Details/5
        [AutorizeUser]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        [AutorizeUser]
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AutorizeUser]
        public ActionResult Create([Bind(Include = "CustomerId,CustName,IsValid,ValidTill,EnteredOnDate,ValidFrom,CustAddress,ContactNo,Email,CustCode,UpdatedOn,UpdatedBy")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                customer.UpdatedOn = DateTime.Today;
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        [AutorizeUser]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AutorizeUser]
        public ActionResult Edit([Bind(Include = "CustomerId,CustName,IsValid,ValidTill,EnteredOnDate,ValidFrom,CustAddress,ContactNo,Email,CustCode,UpdatedOn,UpdatedBy")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        [AutorizeUser]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AutorizeUser]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [AutorizeUser]
        public ActionResult SelectField(int id)
        {
            List<softwareoption> op = db.softwareoptions.Where(x => x.StSchool_SchoolId == id).ToList();
            if (op.Count > 0)
            {
                op[0].StSchool_SchoolId = id;
                DataTable dt = LinqToTable.LINQResultToDataTable(op);
                //ViewData.Model = sopt;
                ViewBag.optlist = dt;
            }
            else
            {
                ViewBag.optlist = null;

            }
            return View();
        }
        [AutorizeUser]
        [HttpPost]
        public ActionResult SelectField(softwareoption op)
        {
            db.Entry(op).State = EntityState.Modified;
            db.SaveChanges();
            List<softwareoption> op1 = db.softwareoptions.Where(x => x.StSchool_SchoolId == op.StSchool_SchoolId).ToList();
            op1[0].StSchool_SchoolId = op.StSchool_SchoolId;
            DataTable dt = LinqToTable.LINQResultToDataTable(op1);
            //ViewData.Model = sopt;
            ViewBag.optlist = dt;
            return View();
        }

        [AutorizeUser]
        public ActionResult School_Index()
        {
            var id = (int)Session["customerid"];
            var name = Session["custname"].ToString();
            var q = db.StoreAPKs.Where(x => x.name.ToLower() == name.ToLower()).FirstOrDefault();
            if (q != null)
            {
                ViewBag.apkname =q.name+"/"+ q.name + ".apk";

            }
            else
            {
                ViewBag.apkname = "citron/citron.apk";
            }

            var schools = db.Schools.Where(s => s.CustomerId == id);
            var a = (from m in db.Schools.ToList().Where(x => x.CustomerId == id)
                     join s in db.Students on m.SchoolId equals s.StSchool_SchoolId
                     select new Student
                     {
                         Size = s.Size,
                         IsPhotoUpload=s.IsPhotoUpload,
                     }).ToList();
            ViewBag.totalsize = a.ToList().Sum(x => x.Size);
            ViewBag.ToalPhoto = a.ToList().Where(x => x.IsPhotoUpload == true).Count();
                return View(schools.ToList());
        }

        [AutorizeUser]
        public ActionResult school_changepassword(int? id)
        {
            Models.Class1.ChangePassword ch = new Models.Class1.ChangePassword();
            ch.id = (int)id;
            return View(ch);
        }

        [HttpPost]
        [AutorizeUser]
        public ActionResult school_changepassword(Models.Class1.ChangePassword ch)
        {
            if(ch.id>0)
            {
                if(ch.ConfirmPassword==ch.NewPassword)
                {
                    var q = db.Schools.Where(x => x.SchoolId == ch.id && x.password == ch.OldPassword).FirstOrDefault();
                    if(q!=null)
                    {
                        q.password = ch.NewPassword;
                        db.Entry(q).State = EntityState.Modified;
                        db.SaveChanges();
                        TempData["smsg"] = "Change Success";

                    }
                    else
                    {
                        TempData["errormsg"] = "Old Password is Wrong..!";
                        return View(ch);
                    }

                }
                else
                {
                    TempData["errormsg"] = "Confirm Password and New Password Not Correct..!";
                    return View(ch);
                }

            }
            else
            {
                TempData["errormsg"] = "Select School..!";
                return View(ch);
            }
            return View(ch);
        }




        [AutorizeUser]
        public ActionResult customer_changepassword(int? id)
        {
            Models.Class1.ChangePassword ch = new Models.Class1.ChangePassword();
            ch.id = (int)Session["customerid"];
            return View(ch);
        }

        [HttpPost]
        [AutorizeUser]
        public ActionResult customer_changepassword(Models.Class1.ChangePassword ch)
        {
                if (ch.ConfirmPassword == ch.NewPassword)
                {
                    var q = db.Customers.Where(x => x.CustomerId == ch.id && x.password == ch.OldPassword).FirstOrDefault();
                    if (q != null)
                    {
                        q.password = ch.NewPassword;
                        db.Entry(q).State = EntityState.Modified;
                        db.SaveChanges();
                        TempData["smsg"] = "Change Success";

                    }
                    else
                    {
                        TempData["errormsg"] = "Old Password is Wrong..!";
                        return View(ch);
                    }

                }
                else
                {
                    TempData["errormsg"] = "Confirm Password and New Password Not Correct..!";
                    return View(ch);
                }
            return View(ch);
        }


        [AutorizeUser]
        public ActionResult School_Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            School school = db.Schools.Find(id);
            if (school == null)
            {
                return HttpNotFound();
            }
            return View(school);
        }

        // GET: Schools/Create
        [AutorizeUser]
        public ActionResult School_Create()
        {
            int customerid = (int)Session["customerid"];
            var q = db.Customers.Where(x => x.CustomerId == customerid).ToList();
            ViewBag.CustomerId = new SelectList(q, "CustomerId", "CustName");
            return View();
        }

        // POST: Schools/Create

WebApplication1/Controllers/StoreAPKsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1;

namespace WebApplication1.Controllers
{
    public class StoreAPKsController : Controller
    {
        private IdCardDataManagerEntities1 db = new IdCardDataManagerEntities1();

        // GET: StoreAPKs
        public ActionResult Index()
        {
            return View(db.StoreAPKs.ToList());
        }

        // GET: StoreAPKs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StoreAPK storeAPK = db.StoreAPKs.Find(id);
            if (storeAPK == null)
            {
                return HttpNotFound();
            }
            return View(storeAPK);
        }

        // GET: StoreAPKs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StoreAPKs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,brand")] StoreAPK storeAPK)
        {
            if (ModelState.IsValid)
            {
                db.StoreAPKs.Add(storeAPK);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(storeAPK);
        }

        // GET: StoreAPKs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StoreAPK storeAPK = db.StoreAPKs.Find(id);
            if (storeAPK == null)
            {
                return HttpNotFound();
            }
            return View(storeAPK);
        }

        // POST: StoreAPKs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,brand")] StoreAPK storeAPK)
        {
            if (ModelState.IsValid)
            {
                db.Entry(storeAPK).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(storeAPK);
        }

        // GET: StoreAPKs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StoreAPK storeAPK = db.StoreAPKs.Find(id);
            if (storeAPK == null)
            {
                return HttpNotFound();
            }
            return View(storeAPK);
        }

        // POST: StoreAPKs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            StoreAPK storeAPK = db.StoreAPKs.Find(id);
            db.StoreAPKs.Remove(storeAPK);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Controllers/renewalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1;

namespace WebApplication1.Controllers
{
    public class renewalsController : Controller
    {
        private IdCardDataManagerEntities1 db = new IdCardDataManagerEntities1();

        // GET: renewals
        public ActionResult Index()
        {
            return View(db.renewals.ToList());
        }

        // GET: renewals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            renewal renewal = db.renewals.Find(id);
            if (renewal == null)
            {
                return HttpNotFound();
            }
            return View(renewal);
        }

        // GET: renewals/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: renewals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,mobile,current_validity,new_validity,customer_amt,dealer_amt,paid,renewal__date")] renewal renewal)
        {
            if (ModelState.IsValid)
            {
                db.renewals.Add(renewal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(renewal);
        }

        // GET: renewals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            renewal renewal = db.renewals.Find(id);
            if (renewal == null)
            {
                return HttpNotFound();
            }
            return View(renewal);
        }

        // POST: renewals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,mobile,current_validity,new_validity,customer_amt,dealer_amt,paid,renewal__date")] renewal renewal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(renewal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(renewal);
        }

        // GET: renewals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            renewal renewal = db.renewals.Find(id);
            if (renewal == null)
            {
                return HttpNotFound();
            }
            return View(renewal);
        }

        // POST: renewals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            renewal renewal = db.renewals.Find(id);
            db.renewals.Remove(renewal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/Shared/Customer.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Id Card Data Collector</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
        <script src="~/Scripts/bootstrap.min.js"></script>*@


</head>
<body style="padding:0;">
    <div class="navbar navbar-inverse navbar-fixed-top" style="background:#0dcaf0">
        <div class="container">
           
            <div class="col-md-12">
                <center>
                    <div class="navbar-collapse collapse" style="display:block;">
                        <ul class="nav navbar-nav" style="display:block;flex-direction:row-reverse;display:flex;">



                            <li style="padding:2%">@Html.ActionLink("Logout", "LogOff", "Account")</li>
                            <li style="padding:2%">@Html.ActionLink("Upload Photos", "UploadPhoto", "Customers")</li>


                            <li style="padding:2%">@Html.ActionLink("Import From Excel", "ImportExcel", "Customers")</li>
                            
                            <li style="padding:2%">@Html.ActionLink("Change Password", "customer_changepassword", "Customers")</li>


                            <li style="padding:2%">@Html.ActionLink("Create Parent Login", "viewparentlogin", "Customers")</li>


                            <li style="padding:2%">@Html.ActionLink("Student", "Student_Index", "Customers")</li>



                            <li style="padding:2%">@Html.ActionLink("Add School", "School_Create", "Customers")</li>

                            <li style="padding:2%;">
                                <a href="~/Customers/School_Index">Home</a>
                            </li>
                        </ul>

                    </div>
                </center>
            </div>
          
        </div>
    </div>
    @*@Html.Partial("_LoginPartial")*@
    <div class="container body-content">
        <br />
        @if (TempData["errormsg"] != null)
        {
            <div id="floating-top-container" class="floating-container AlertBoxCloser">
                <div id="floating-top-center">
                    <div class="alert-wrap animated jellyIn in">
                        <div class="alert alert-danger" role="alert">
                            <div id="actionAlert" class="media">
                                <strong>Alert! </strong> @TempData["errormsg"]
                            </div>
                        </div>
                    </div>
                </div>
                <div id="floating-top-left"></div>
            </div>
        }
        @if (TempData["smsg"] != null)
        {
            <div id="floating-top-container" class="floating-container AlertBoxCloser">
                <div id="floating-top-center">
                    <div class="alert-wrap animated jellyIn in">
                        <div class="alert alert-success" role="alert">
                            <div id="actionAlert" class="media">
                                <strong>Success! </strong> @TempData["smsg"]
                            </div>
                        </div>
                    </div>
                </div>
                <div id="floating-top-left"></div>
            </div>
        }


        @RenderBody()
        <hr />

        <footer>
            <p>&copy; @DateTime.Now.Year - Citron Softwares</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)


</body>
</html>

WebApplication1/Views/Shared/Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Id Card Data Collector</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
        <script src="~/Scripts/bootstrap.min.js"></script>*@


</head>
<body style="background-color:cornsilk">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>*@
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li style="padding:1%">@Html.ActionLink("User", "Index", "Users")</li>
                    <li style="padding:1%">@Html.ActionLink("Student", "Index", "Students")</li>
                    <li style="padding:1%">@Html.ActionLink("Schools", "Index", "Schools")</li>

                    <li style="padding:1%">@Html.ActionLink("About", "About", "Home")</li>

                    <li style="padding:1%">@Html.ActionLink("Home", "Index", "Home")</li>

                </ul>

            </div>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
    
    <div class="container body-content">
        @RenderBody()
       
        @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)


</body>
</html>

WebApplication1/Views/Shared/School.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Id Card Data Collector</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
        <script src="~/Scripts/bootstrap.min.js"></script>*@


</head>
<body style="padding:0;">
    <div class="navbar navbar-inverse navbar-fixed-top"  style="background:#0dcaf0">
        <div class="container">

            <div class="col-md-2"></div>
            <div class="col-md-8">
                <center>
                    <div class="navbar-collapse collapse" style="display:block;">
                        <ul class="nav navbar-nav" style="display:block;flex-direction:row-reverse;display:flex;">



                            <li style="padding:3%">@Html.ActionLink("Logout", "LogOff", "Account")</li>
                            <li style="padding:3%"><a href="~/Students/school_changepassword">Change Password</a></li>

                            <li style="padding:3%"><a href="~/Students/ImportExcel">Import From Excel</a></li>

                            <li style="padding:3%"> <a href="~/Students/Index">Student</a></li>



                        </ul>

                    </div>
                </center>
            </div>
            <div class="col-md-2"></div>

        </div>
            </div>
        
    
    <div class="container body-content">
        <br />
        @if (TempData["errormsg"] != null)
        {
            <div id="floating-top-container" class="floating-container AlertBoxCloser">
                <div id="floating-top-center">
                    <div class="alert-wrap animated jellyIn in">
                        <div class="alert alert-danger" role="alert">
                            <div id="actionAlert" class="media">
                                <strong>Alert! </strong> @TempData["errormsg"]
                            </div>
                        </div>
                    </div>
                </div>
                <div id="floating-top-left"></div>
            </div>
        }
        @if (TempData["smsg"] != null)
        {
            <div id="floating-top-container" class="floating-container AlertBoxCloser">
                <div id="floating-top-center">
                    <div class="alert-wrap animated jellyIn in">
                        <div class="alert alert-success" role="alert">
                            <div id="actionAlert" class="media">
                                <strong>Success! </strong> @TempData["smsg"]
                            </div>
                        </div>
                    </div>
                </div>
                <div id="floating-top-left"></div>
            </div>
        }

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Citron Softwares</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)


</body>
</html>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Id Card Data Collector</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
        <script src="~/Scripts/bootstrap.min.js"></script>*@


    
</head>
<body >
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Citron Id Card Data Collector", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse" style="display:block;">
                <ul class="nav navbar-nav" style="display:block;flex-direction:row-reverse;display:flex;">
                    <li style="padding:1%">@Html.ActionLink("Logout", "LogOff", "Account")</li>
                    <li style="padding:1%">@Html.ActionLink("ChangePassword", "ChangePassword", "Users")</li>
                    <li style="padding:1%">@Html.ActionLink("Add APK", "Index", "StoreAPKs")</li>
                    <li style="padding:1%">@Html.ActionLink("Renewal List", "Index", "renewals")</li>
                    <li style="padding:1%">@Html.ActionLink("Dealers", "Index", "Dealers")</li>
                    <li style="padding:1%">@Html.ActionLink("Add Customer", "Create", "Users")</li>
                    <li style="padding:1%">@Html.ActionLink("Customers", "Index", "Users")</li>

                </ul>

            </div>
        </div>
    </div>
    @*@Html.Partial("_LoginPartial")*@
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year </p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)


</body>
</html>